sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t anastasiya108/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true anastasiya108/docker-react npm run test